### 인덱싱 / 슬라이싱
- 하나의 대괄호에 쉼표로 다차원 배열의 인덱스를 표기함
- numpy 배열 슬라이싱의 결과는 원본의 참조임 $\to$ 슬라이싱의 결과값을 바꾸면 원본도 바뀜

In [9]:
import numpy as np

In [4]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a[1] # 인덱싱 

array([4, 5, 6, 7])

In [6]:
a[2,3] # python list의 인덱싱: a[2][3]

np.int64(11)

In [7]:
b=a[0:2, 1:3] # 슬라이싱 a[0][1], a[0][2], a[1][1], a[1][2]
b

array([[1, 2],
       [5, 6]])

In [6]:
b[0]=99
b

array([[99, 99],
       [ 5,  6]])

In [7]:
a # 슬라이싱은 원본의 참조이므로 값을 변경하면 원본도 변경됨

array([[ 0, 99, 99,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 파이썬 리스트의 슬라이싱

In [8]:
la=[1,2,3,4]
lb=la[1:3]
lb

[2, 3]

In [9]:
lb[0]=100
lb

[100, 3]

In [10]:
la

[1, 2, 3, 4]

- 영상처리에서 슬라이싱은 이미지의 일부분을 처리하기 위해 사용되기에 원본을 유지하는 것보다<br>numpy의 참조 방식으로 슬라이싱한 부분을 처리하여 원본이 수정되는 방식을 사용하는 것이 유리

In [4]:
a=np.arange(12).reshape(3,4)

In [5]:
c=a[0:2,1:3].copy() # 원본을 바꾸지 않으려면 복사를 해야함
c

array([[1, 2],
       [5, 6]])

In [6]:
c[0]=99
c

array([[99, 99],
       [ 5,  6]])

In [7]:
a # 원본이 바뀌지 않음

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 펜시 인덱싱
- 접근하고자 하는 위치의 인덱스를 리스트로 만들어 전달
- 전달하는 배열이 숫자이면 해당 숫자 인덱스의 값이 선택됨
- 전달하는 배열이 bool이면 True가 있는 위치의 인덱스들이 전달되어 요소를 선택하게 함

In [9]:
a=np.arange(3,8)
a

array([3, 4, 5, 6, 7])

In [10]:
a[[1,3,4]]

array([4, 6, 7])

In [11]:
b=[1,2,3]
a[b] # 리스트형 변수를 사용해도 됨

array([4, 5, 6])

In [12]:
a[[True, False, True, False, True]] # bool인 경우에는 배열의 크기와 같아야 함

array([3, 5, 7])

In [13]:
a=np.arange(10)
b=a>5
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [14]:
a[b]

array([6, 7, 8, 9])

In [15]:
a[a>5]

array([6, 7, 8, 9])

In [16]:
a[a>5]=1 # 원하는 위치에 특정한 값을 할당하는 방법
a
# 127 이상의 값을 255로, 127 미만의 값을 0으로 하면 흑백 => 이진화(2줄만으로 가능함)

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [17]:
a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
a[[3],[5]] # (3,5)

array([23])

In [25]:
a[[0,2],[2,3]] # (0,2), (2,3)

array([ 2, 15])

In [12]:
b=np.arange(30).reshape(2,5,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [27]:
b[[0,1],[2,3],[1,2]] # (0,2,1), (1,1,2)

array([ 7, 26])

In [39]:
b[[0,1,0,0,1], np.arange(5), np.random.randint(0,3,(5,))] # rand로 인해 출력할 때마다 값이 다름

array([ 0, 19,  8, 10, 28])

### 병합
- hstack(arrays): 수평으로 병합 arrays는 병합 대상 배열들로 이루어진 튜플임(옆으로 붙임)
- vstack(arrays): 수직으로 병합(아래로 붙임)
- concatenate(arrays, axis=0): 지정한 축 기준으로 병합
- stack(arrays, axis=0): 새로운 축으로 병합

In [29]:
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [30]:
b=np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [31]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [32]:
np.hstack((a,b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

* 3차원 배열에서 hstack, vstack

In [19]:
c=np.arange(12).reshape(2,2,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [20]:
d=np.arange(10,22).reshape(2,2,3)
d

array([[[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21]]])

In [23]:
e=np.hstack((c,d))
e

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [10, 11, 12],
        [13, 14, 15]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [16, 17, 18],
        [19, 20, 21]]])

In [24]:
e.shape

(2, 4, 3)

In [26]:
f=np.vstack((c,d))
f

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21]]])

In [27]:
f.shape

(4, 2, 3)

In [33]:
np.concatenate((a,b),0) # == vstack() - 수평 병합

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [34]:
np.concatenate((a,b),1) # == hstack() - 수직 병합

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [35]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
b=np.arange(10,130,10).reshape(4,3)
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [37]:
np.stack((a,b),0) # 0번 축이 새로 생기면서 a,b 병합

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [38]:
np.stack((a,b),1) # 1번 축으로 a,b 병합

array([[[  0,   1,   2],
        [ 10,  20,  30]],

       [[  3,   4,   5],
        [ 40,  50,  60]],

       [[  6,   7,   8],
        [ 70,  80,  90]],

       [[  9,  10,  11],
        [100, 110, 120]]])

In [39]:
np.stack((a,b),2) # 2번 축으로 a,b 병합

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

### 분리
- vsplit(array, indice): 수평으로 분리, indice는 분리할 개수 또는 인덱스
- hsplit(array, indice): 수직으로 분리
- split(array, indice, axis=0): 지정한 축으로 분리

In [29]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.hsplit(a,3) # 균등 분할(3조각으로 나눔)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [33]:
np.hsplit(a,(3,6)) # [:3], [3:6], [6:]으로 자름

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [34]:
np.split(a,3,0) # 3조각으로 나누되 axis=0으로 자름(1차원이라 (a,3)과 같은 값 출력)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [31]:
np.split(a,[3,6,9],0)
# 인덱스로 분할 [3,6,9]라는 인덱스 기준으로 잘라서 나눔
# [0:3],[3:6],[6:9],[9:]와 동일

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

- 1차원 배열에서는 y축으로는 한 줄 밖에 없기에 vsplit을 쓸 수 없음

In [35]:
# a=np.arange(12)
# np.vsplit(a,3) => 2차원부터 vsplit() 가능, 따라서 오류가 발생

In [36]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
np.vsplit(b,2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [39]:
np.split(b,2,0 ) # 0번축은 y축, 즉 vsplit과 동일

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [40]:
np.vsplit(b,[1])

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [41]:
np.hsplit(b,[1])

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [42]:
np.split(b,[1],1) # 1번 축은 x축, 즉 hsplit()과 동일

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

### 검색 기능
- where(condition [,t,f]): 조건에 맞는 요소 찾기
  - condition: 검색에 사용할 조건식
  - t: 조건에 맞는 값에 지정할 값이나 배열
  - f: 조건에 틀린 값에 지정할 값이나 배열
- nonzero(array): 요소 중에 0이 아닌 요소의 인덱스의 배열을 반환
- all(array [, axis]): 모든 요소가 True인지 검색
- any(array [, axis]): 어느 요소이든 True가 있는지 검색

-픽셀값(밝기값)의 크기로 픽셀들을 나누거나 어떤 처리를 해야 할 때 사용하면 처리가 쉬움

In [46]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
coords=np.where(a>6)
coords # 다차원 배열인 경우에은 각 축의 인덱스 값의 배열들을 리턴

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [48]:
np.stack((coords[0], coords[1]),-1) # 좌표로 사용하려면 stack() 함수를 사용해 병합

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]])

In [49]:
b=np.array([0,1,2,0,1,2])
np.nonzero(b) # 1차원 배열인 경우, 인덱스들의 배열을 리턴

(array([1, 2, 4, 5]),)

In [50]:
c=np.array([[0,1,2],[1,2,0],[2,0,1]])
c

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [51]:
coords=np.nonzero(c)
coords

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 0, 2]))

In [52]:
np.stack((coords[0],coords[1]), -1)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]])

In [43]:
d=np.array([[[True, False, True, True],
             [True, True, False, True],
             [True, True, True, True]],
            [[True, True, True, True],
             [True, False, True, True],
             [True, True, True, True]]])
d

array([[[ True, False,  True,  True],
        [ True,  True, False,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True, False,  True,  True],
        [ True,  True,  True,  True]]])

In [45]:
d.shape

(2, 3, 4)

In [52]:
np.all(d,0) # 0차원 축 기준으로 모든 요소가 True이면 True, 즉 (0,0,0)의 값과 (1,0,0)의 값이 모두 True이므로 (0,0) 위치에 True 출력

array([[ True, False,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True]])

In [51]:
np.all(d,1) # 1차원 축 기준으로 모든 요소가 True이면 True, ex.(1,0,1), (1,1,1), (1,2,1)의 값이 (T,F,T)이므로 (1,1) 위치에 False 출력

array([[ True, False, False,  True],
       [ True, False,  True,  True]])

In [54]:
np.all(d,2) # 2차원 축 기준으로 모든 요소가 True이면 True, ex.(1,1,0), (1,1,1), (1,1,2)의 값이 (T,T,F)이므로 (1,1) 위치에 False 출력

array([[False, False,  True],
       [ True, False,  True]])

In [56]:
a=np.arange(10)
b=np.arange(10)
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [57]:
np.all(a==b)

np.True_

In [58]:
b[5]=-1
b

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

In [60]:
np.all(a==b)

np.False_

In [61]:
np.any(d)

np.True_

In [62]:
np.any(d,1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### 기초 통계 함수
- sum(array [, axis]): 배열의 합계
- mean(array [, axis]): 배열의 평균
- amin(array [, axiz]): 배열의 최소값, min()과 동일
- amax(array [, axis]): 배열의 최대값, max()와 동일

In [64]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.sum(a)

np.int64(66)

In [66]:
np.sum(a,0)

array([12, 15, 18, 21])

In [67]:
np.sum(a,1)

array([ 6, 22, 38])

In [68]:
np.mean(a)

np.float64(5.5)

In [69]:
np.mean(a,0)

array([4., 5., 6., 7.])

In [71]:
np.mean(a,1)

array([1.5, 5.5, 9.5])

In [72]:
np.amin(a)

np.int64(0)

In [74]:
np.amin(a,0)

array([0, 1, 2, 3])

In [73]:
np.amin(a,1)

array([0, 4, 8])

In [75]:
np.amax(a)

np.int64(11)

In [77]:
np.amax(a,0)

array([ 8,  9, 10, 11])

In [78]:
np.amax(a,1)

array([ 3,  7, 11])

Numpy와 OpenCV의 좌표 차이에 주의
 - Numpy: (i,j) -> 배열 인덱스[Height, Width]
 - OpenCV: (x,y) -> 직교 좌표계 [Width, Height]

- 영상처리: 입력된 영상을 어떤 목적을 위해 처리하는 기술
- 영상(image): 밝기와 색상이 다른 일정한 수의 화소들의 모음
- 화소(pixel): 영상의 최소 단위 구성 요소

- 영상처리
  - 어떤 목적을 위해 연산을 이용해 화소들에 대해 변화를 주는 것
  - 과거: 아날로그
  - 현재: 디지털
     - 디지털 영상은 밝기값과 위치값을 가진 일정 수의 화소들로 구성

- 정지된 이미지를 연속적으로 보여줘서 움직이는 것처럼 보이게 함
- 프레임 정보를 그대로 저장하지 않음
  - 한 프레임 이후 다음 프레임의 차이가 발생하고 그 차이를 저장

### 영상처리 수준
- 처리 결과가 영상 자체: 저 수준의 영상 처리
- 처리 결과가 영상의 특성들: 고 수준의 영상 처리

### 저 수준의 영상 처리
- 영상 획득: 실제 장면을 디지털 영상으로 바꾸는 과정
- 영상 향상: 영상을 보기 좋게 만드는 과정
- 영상 복원: 손상된 영상을 원래처럼 되돌리는 과정
- 변환 처리: 픽셀 도메인을 주파수 도메인으로 바꾸는 과정
- 영상 압축: 영상 크기를 줄여 저장·전송을 쉽게 하는 과정

### 고 수준의 영상 처리
- 영상 분할: 의미있는 객체나 영역을 분리하는 과정
- 영상 표현: 분할된 객체나 영역을 수학적, 기하학적, 구조적 형태로 표현
  - 영상의 이미지가 어떤 이미지인지 설명(ex. 이 영상은 파란색이 많음)
- 영상 인식: 표현된 객체를 분류하고 의미를 부여하는 과정
  - 이게 무엇인가를 알아내는 것

### 처리 방법에 따른 기술 분류
- 화소 점 처리: 각 픽셀 단위로 독립적으로 처리, 한 픽셀의 출력은 그 픽셀의 입력값에 의존
- 화소 영역 처리: 한 픽셀을 처리할 때 그 주변 영역을 함께 고려(필터링)
- 기하학적 처리: 영상 전체의 좌표계 변환 수행, 픽셀값은 유지하고 (x,y)를 변화
- 변환 처리: 픽셀 도메인을 주파수 도메인으로 변환
- 프레임 처리: 단일 영상이 아닌 시간에 따라 연속된 영상(프레임)을 처리
  - 한 프레임과 다른 프레임의 관계를 처리

### 영상처리 관련 분야
- 영상 처리: 입력 영상을 처리해 출력으로 처리된 영상
- 컴퓨터 그래픽스: 데이터를 사용해 원하는 영상을 만들어 내는 기술
- 컴퓨터 비전: 기본적인 영상처리를 바탕으로 영상에서 특정한 정보를 추출해 처리하는 기술

### 영상의 형성 과정
- 샘플링: 무한한 연속된 값을 일정한 해상도에 따라 유한 개의 화소 수만큼 입력값을 취하는 과정
- 양자화: 제한된 비트 수로 화소 값을 나타내기 위해 밝기값을 정수화시키는 과정

- 이 두 과정은 동시에 일어남 $\to$ 뽑자마자 자르고 저장함

### 디지털 영상 표현
- opencv에서는 (x, y)의 형태라면 numpy는 화소들의 집합이 M x N 크기의 영상으로 표현됨

### OpenCV
- 영상처리와 컴퓨터 비전 관련 오픈소스 라이브러리
- 영상처리, 컴퓨터 비전 및 기계 학습과 관련된 전통적인 알고리즘
- 얼굴 검출과 인식, 객체 인식, 객체의 3D 모델 추출, 스테레오 카메라에서 3D 좌표 생성
- 고해상도 영상 생성을 위한 이미지 스티칭, 영상 검색, 적목 현상 제거, 안구 운동 추척 등 다양한 응용 분야에 사용
- 4.7만 이상의 사용자 그룹과 1800만 번 이상의 다운로드 횟수

In [57]:
import numpy as np
import cv2

image=np.zeros((200,400), np.uint8)
image[:]=200

title1, title2='Position1','Position2'
cv2.namedWindow(title1, cv2.WINDOW_AUTOSIZE)
cv2.namedWindow(title2, cv2.WINDOW_NORMAL)
cv2.waitKey(0)

cv2.moveWindow(title1, 150, 150)
cv2.moveWindow(title2, 400, 50)
cv2.waitKey(0)

cv2.imshow(title1, image)
cv2.imshow(title2, image)
cv2.waitKey(0)

cv2.resizeWindow(title1, 600, 300)
cv2.resizeWindow(title2, 600, 300)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [58]:
import numpy as np
import cv2

## switch case문을 사전(dictionary)으로 구현
switch_case = {
	ord('a'): "a키 입력",               		# ord() 함수- 문자를 아스키코드로 변환
  	ord('b'): "b키 입력",
  0x41: "A키 입력",
  int('0x42', 16): "B키 입력",          		# 16진수인 0x42를 10진수로 변환하면 66임
  2424832: "왼쪽 화살표키 입력",      		    # 0x250000
  2490368: "윗쪽 화살표키 입력",      		    # 0x260000
  2555904: "오른쪽 화살표키 입력",    		    # 0x270000
  2621440: "아래쪽 화살표키 입력"        		# 0x280000
}

image = np.ones((200, 300), np.float64)      	# 화소값이 1인 행렬 생성
cv2.namedWindow('Keyboard Event')			# 윈도우 이름
cv2.imshow('Keyboard Event', image)

while True:									# 무한 반복
    key = cv2.waitKeyEx(100)          		# 100ms 동안 키 이벤트 대기
    if key == 27: break                		# ESC 키 누르면 종료

    try:
        result = switch_case[key]
        print(result)
    except KeyError:
        result = -1

cv2.destroyAllWindows()              	# 열린 모든 윈도우 제거

In [59]:
# def onMouse(event, x, t, flags, param):
#    ...
#cv2.setMouseCallback(title, onMouse)

In [ ]:
import numpy as np
import cv2

def onMouse(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print("마우스 왼쪽 버튼")
        if flags & cv2.EVENT_FLAG_CTRLKEY:
            print('ctrl 키')
    elif event == cv2.EVENT_RBUTTONDOWN:
        print("마우스 오른쪽 버튼")
    elif event == cv2. EVENT_RBUTTONUP:
        print("마우스 오른쪽 버튼 때기")
    elif event == cv2.EVENT_LBUTTONDBLCLK:
        print("마우스 왼쪽 버튼 더블클릭")

image = np.full((200, 300), 255, np.uint8)

title1, title2 = "Mouse Evnet1", "Mouse Event2"
cv2.imshow(title1, image)
cv2.imshow(title2, image)

cv2.setMouseCallback(title1, onMouse)
cv2.waitKey(0)
cv2.destroyAllWindows()